### ISSUE TITLE
database into publication page

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/readchina.github.io#142]
Hi @duncdrum I think we should add the database to our publications page, right?

**Comment by damianodamiani** [comment]
should I do this? or outdated?

**Comment by LenaHenningsen** [comment]
Yes please

 

Von: Damian M ***@***.***>
Antworten an: "readchina/readchina.github.io" ***@***.***>
Datum: Donnerstag, 23. November 2023 um 12:02
An: "readchina/readchina.github.io" ***@***.***>
Cc: Lena Henningsen ***@***.***>, Author ***@***.***>
Betreff: Re: [readchina/readchina.github.io] database into publication page (#142)

 

should I do this? or outdated?

**Comment by damianodamiani** [comment]
via #302
