### ISSUE TITLE
Two Sass warnings

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/readchina.github.io#266]
Two types of warning appeared:

1. `@elseif is deprecated and will not be supported in future Sass versions.`
2. `Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`

It is not urgent to fix but eventually they should be fixed.

<img width="1048" alt="Screenshot 2023-02-22 at 17 08 03" src="https://user-images.githubusercontent.com/46596921/220685046-54014ab5-18a0-4d95-86a6-d75e3b2c613e.png">

- [x] `@elseif `
- [ ]  replace div with calc() or math.div()

**Comment by damianodamiani** [comment]
what's the status on this issue?

**Comment by whalekeykeeper** [comment]
Currently am trying to use the[ sass-migrator ](https://sass-lang.com/documentation/cli/migrator/)for fix the division problem

**Comment by whalekeykeeper** [comment]
> Currently am trying to use the[ sass-migrator ](https://sass-lang.com/documentation/cli/migrator/)for fix the division problem

It's not an error but just a warning. I guess we can leave it there.
