### ISSUE TITLE
Add Shouchaoben tile

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/readchina.github.io#269]
A tile should be added to the home page of this site.
It should be named as `Shouchaoben` and should be directed to the [Shouchaoben](https://readchina.github.io/shouchaoben/) page.

**Comment by damianodamiani** [comment]
hey, so: I don't see the tile, has it been taken down? or some bug/issue? 

+ we could add here issue #193 and fill that empty space in your screenshot with yet another tile, about our AUP publication series. if you could fix the issue here and add that second tile (can be empty or lorem impsum) @whalekeykeeper I could then fill it with relevant content

**Comment by whalekeykeeper** [comment]
> hey, so: I don't see the tile, has it been taken down? or some bug/issue?
> 
> we could add here issue #193 and fill that empty space in your screenshot with yet another tile, about our AUP publication series. if you could fix the issue here and add that second tile (can be empty or lorem impsum) @whalekeykeeper I could then fill it with relevant content

I am working on the new tile now. Sounds like a quite nice idea. I will have a look and come back to you soon.

**Comment by damianodamiani** [comment]
no rush :) thanks! the series could be as https://readchina.github.io/aup-series/ or soemthing like this, and follow the standard layout of the page, probably could just copy https://readchina.github.io/about.html or something

**Comment by whalekeykeeper** [comment]
> it's about this, for context: https://www.aup.nl/en/series/practices-and-politics-of-reading-in-china

I added a new tile, how should we name it?
The temporary name is "AUP publication series", could be modified easily.
See the screenshot:
<img width="1614" alt="Screenshot 2023-11-29 at 06 05 54" src="https://github.com/readchina/readchina.github.io/assets/46596921/cf2dafc4-565b-418d-ab2e-ef720c8f2675">
And once the new tile is clicked:
<img width="1603" alt="Screenshot 2023-11-29 at 06 06 05" src="https://github.com/readchina/readchina.github.io/assets/46596921/ff14d387-2d82-43f7-aebe-3fec468ef61d">

**Comment by damianodamiani** [comment]
hey, thanks! looks good, I also think we can just link directly to the AUP website, good idea. perhaps we could name the tile "AUP Book Series: Practices and Politics of Reading in China" and then "READCHINA x Amsterdam University Press" in the subtitle?

**Comment by whalekeykeeper** [comment]
Sure. Nice idea!
<img width="1601" alt="Screenshot 2023-11-29 at 22 40 31" src="https://github.com/readchina/readchina.github.io/assets/46596921/f6595e18-aa85-469b-83ce-3c7f1f27d80c">
