### ISSUE TITLE
minor typo on the read act homepage

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/readchina.github.io#275]
on
https://readchina.github.io/readact.html

in the paragraph following the header

High-level view of the database

please change 

, etc. Which connects 

 to 

, etc. which connects

**Comment by LenaHenningsen** [comment]
Thanks (and no need to hurry)

**Comment by LenaHenningsen** [comment]
And another ReadAct question: can you see where the large number of mentionings of gadfly come from? Do they result from the fact that the fictional reading acts are included now? I just realize that now the text above does not fit the results we display below... can we display ONLY the reading acts that stem from the autobiographical? And maybe then another one with the full set? Thanks a lot and have a good week everyone...

**Comment by whalekeykeeper** [comment]
> And another ReadAct question: can you see where the large number of mentionings of gadfly come from? Do they result from the fact that the fictional reading acts are included now? I just realize that now the text above does not fit the results we display below... can we display ONLY the reading acts that stem from the autobiographical? And maybe then another one with the full set? Thanks a lot and have a good week everyone...

I had a look at [ReadAct](https://github.com/readchina/ReadAct/blob/master/csv/data/Act.csv#L362). All the 20 entries of ReadAct which related to ``The Gadfly'' were not fictional ones.

**Comment by whalekeykeeper** [comment]
True.
I had another look. For example, [line 1126 in Act.csv](https://github.com/readchina/ReadAct/blob/master/csv/data/Act.csv#1126) has the `Agent` `AG0677` and `fictionality` value `null`, however, this `AG0677` in the [Agent table](https://github.com/readchina/ReadAct/blob/master/csv/data/Agent.csv#678) has its value of `fictionality` as `F`.

**Comment by duncdrum** [comment]
@whalekeykeeper this is most likely not a mismatch. Agent, Act and Object can have their status set independently, only acts with non-fictional agents, and objects, would have `F` in the Acts table, to signal that the act was recorded based on a fictional source. Fictional agents or objects, always make for fictional acts. 

If you want to change the data model, i would suggest moving from boolean to num, and aggregate over the number of `F` for the entities, which can than be recorded in the Act table .

**Comment by whalekeykeeper** [comment]
> 

Now I get that Agent, Act, and Object can have independent fictional-or-not status.  Thanks.

What entities should be aggregate for the Act table?

**Comment by duncdrum** [comment]
They should only be aggregate if you want to change the data model. Otherwise you need to adjust your query to determin fictional acts by checking the ontological status of Agent, Act, and Object, any ´F´ will mark the individual act as fictional

**Comment by LenaHenningsen** [comment]
Thanks both of you. I vaguely can follow the discussion. Does that mean, if we change the query we will get the results displayed as they were orginally? And then we could do the other charts as I suggest in issue #277 ?

**Comment by whalekeykeeper** [comment]
The typo is fixed.

**Comment by LenaHenningsen** [comment]
done

 

Von: Damian M ***@***.***>
Antworten an: "readchina/readchina.github.io" ***@***.***>
Datum: Donnerstag, 23. November 2023 um 12:08
An: "readchina/readchina.github.io" ***@***.***>
Cc: Lena Henningsen ***@***.***>, Author ***@***.***>
Betreff: Re: [readchina/readchina.github.io] minor typo on the read act homepage (Issue #275)

 

is this issue still open? relevant? outdated? solved?
