### ISSUE TITLE
Fictional / non-fictional RA displayed on web-page

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/readchina.github.io#277]
At the moment, the webpage text and data representation do not match; at least for the Gadfly, the fictional RA appear in the chart, while the text refers to only the RA from autobiographical sources; and as a consequence, the numbers do not match either. So can we have in that position the original data set, i.e. only autobiographies, and then below
- one only fictional RA
- maybe one with only RA from SF
- one that aggregates all?
Thanks and this is a to do for when shouchaoben are up and running.

**Comment by LenaHenningsen** [comment]
@duncdrum we may need your help on the issue with the fictional RA that appear below this text:

The previous views look at individual works, to determine popular creators, we need to group works belonging to the same author together. It should come as no surprise that Mao Zedong is the most popular creator of works being read within our data-set. However, looking at other popular choices, we see that next to Karl Marx (another usual suspect), Lu Xun and Alexandre Dumas are on equal footing.

Ideally, revert the chart to a chart without the fictional RA, then continue; 
and then a new subheading above the conclusion.
Fictional reading acts (AS A SUBHEADING)
The ReadAct database also allows the chronicling of fictional reading acts, i.e. inputting reading acts by fictional characters in pieces of fiction. While the reading acts may be similar to those chronicled in autobiographical sources, they pose methodological questions for the data model pertaining to truth values and claims to reality: What if a fictional character is described reading a text by a real author that never existed in reality, say Harry Potter reading a romantic love story by Mao Zedong? What if a purportedly real but fictionally presented person who appears in a fictional text is reading something he or she never read in real life? ReadAct takes this into account by marking the fictionality of the respective act. As of this writing (May 2023), only a limited subset of Chinese literature has been recorded in the database, consisting mostly of Science Fiction stories. The prominent position of Ethel Voynich and her novel _The Gadfly_, however can be traced back to the short story "The Class Teacher" (班主任, 1977) by Liu Xinwu in which the protagonists read and discuss the novel elaborately. 
>>> then chart with only the fictional reading acts
>>> then chart with 
Popular authors in fictional reading acts

(((Once they are there, I would like to add a few words to them).

**Comment by damianodamiani** [comment]
what's the status on this issue?

**Comment by whalekeykeeper** [comment]
I think it's fixed.

**Comment by LenaHenningsen** [comment]
I think this is done.

 

Von: Damian M ***@***.***>
Antworten an: "readchina/readchina.github.io" ***@***.***>
Datum: Donnerstag, 23. November 2023 um 12:08
An: "readchina/readchina.github.io" ***@***.***>
Cc: Lena Henningsen ***@***.***>, Assign ***@***.***>
Betreff: Re: [readchina/readchina.github.io] Fictional / non-fictional RA displayed on web-page (Issue #277)

 

what's the status on this issue?
