### ISSUE TITLE
vega editor not working?

### ISSUE THREAD

**Issue by damianodamiani** [readchina/readchina.github.io#300]
hey, maybe im doing something wrong, but when I follow the invitation to explore the ReadAct db in vega, I see nothing:

<img width="1440" alt="Screenshot 2023-11-23 at 11 58 47" src="https://github.com/readchina/readchina.github.io/assets/35594124/f8210f3b-558b-413f-b34c-d5fdd48cd0f3">

**Comment by duncdrum** [comment]
@damianodamiani which visualization did you try to load ?

**Comment by duncdrum** [comment]
did you click "run"?

**Comment by damianodamiani** [comment]
i did not, ha! ok so all good, closing
